logo = true
logoText = "TCCK"
logoType = "short" # long, short
description = "Tai Chi Chuan, Chi Kung, Yoga."
custom_css = []
custom_js = []
useFaviconGenerator = false # https://www.favicon-generator.org/
meta_image = ""

# theme
themecolor = ""
themeOptions = ["dark", "light", "hacker", "solarized", "kimbie"]
enableThemeChange = true

notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

viewportSize = "normal" # widest, wider, wide, normal, narrow
enableUiAnimation = false
hideSingleContentsWhenJSDisabled = false
enablePinnedPosts = false
minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

# header
homeHeaderType = "text" # text, img, slide, typewriter

# menu
#showMobileMenuTerms = ["tags", "categories", "series"]
showMobileMenuTerms = []

# body
enableBreadcrumb = true
enablePhotoSwipe = false
enableSearch = true
enableSearchHighlight = false
enableGoToTop = true
enableWhoami = false
summaryShape = "classic" # card, classic, compact
searchResultPosition = "main" # side, main
archiveGroupByDate = "2006" # "2006-01": group by month, "2006": group by year
archivePaginate = 13
paginateWindow = 1
talksPaginate = 5
talksGroupByDate = "2006"
pubPaginate = 20

# whoami
myname = "Jeremías"
email = ""
whoami = "Tai Chi Chuan, Chi Kung, Yoga."
bioImageUrl = ""
useGravatar = false
location = "Montevideo, Uruguay."
organization = ""
link = ""

# sidebar
enableBio = false
enableBioImage = false
enableSidebar = false
enableSidebarTags = false
enableSidebarSeries = false
enableSidebarCategories = false
enableHomeSidebarTitles = false
enableListSidebarTitles = false
enableToc = false
hideToc = false
tocFolding = true
tocPosition = "inner" # inner, outer
enableTocSwitch = false
itemsPerCategory = 5
sidebarPosition = "right"
tocLevels = ["h2", "h3", "h4"]
enableSidebarPostsByOrder = false

# footer
showPoweredBy = true
showFeedLinks = false
showSocialLinks = true
enableLangChange = false

# service
googleTagManager = "" # GTM-XXXXXX
baiduAnalytics = ""
enableBusuanzi = false
busuanziSiteUV = false
busuanziSitePV = false
busuanziPagePV = false

# rss
updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
updateFrequency = ""
fullContents = false

# comment
enableComment = false
disqus_shortname = ""
commento = false

[socialOptions]
  email = "mailto:jeremias.tcck@gmail.com"
  phone = "tel:+59892916460"
  whatsapp = "https://wa.me/59892916460"
  instagram = "https://instagram.com/tcck.uy/"
  github = ""
  facebook = ""
  twitter = ""
  stack-overflow = ""
  google-plus = ""
  youtube = ""
  medium = ""
  tumblr = ""
  linkedin = ""
  pinterest = ""
  stack-exchange = ""
  telegram = ""
  steam = ""
  weibo = ""
  douban = ""
  csdn = ""
  gitlab = ""
  mastodon = ""
  jianshu = ""
  zhihu = ""
  signal = ""
  matrix = ""
  xmpp = ""
  dev-to = ""
  gitea = ""
  google-scholar = ""

[copyrightOptions]
  enableCopyrightLink = true
  copyrightLink = "https://creativecommons.org/publicdomain/zero/1.0/"
  copyrightLinkImage = ""
  copyrightLinkText = " CC0 1.0"
